# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kasir.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'kasir.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bkasir.proto\x12\x05kasir\"J\n\x12TransactionRequest\x12\x0c\n\x04item\x18\x01 \x01(\t\x12\x0e\n\x06jumlah\x18\x02 \x01(\x05\x12\x16\n\x0eharga_per_unit\x18\x03 \x01(\x02\"o\n\x13TransactionResponse\x12\x13\n\x0btotal_harga\x18\x01 \x01(\x02\x12\x0e\n\x06\x64iskon\x18\x02 \x01(\x02\x12\r\n\x05pajak\x18\x03 \x01(\x02\x12\x13\n\x0bharga_akhir\x18\x04 \x01(\x02\x12\x0f\n\x07message\x18\x05 \x01(\t\"\x1a\n\nStockQuery\x12\x0c\n\x04item\x18\x01 \x01(\t\"<\n\rStockResponse\x12\x0c\n\x04item\x18\x01 \x01(\t\x12\x0c\n\x04stok\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"2\n\x12StockUpdateRequest\x12\x0c\n\x04item\x18\x01 \x01(\t\x12\x0e\n\x06jumlah\x18\x02 \x01(\x05\"&\n\x13StockUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"8\n\x10TransactionQuery\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x02 \x01(\t\"g\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04item\x18\x02 \x01(\t\x12\x0e\n\x06jumlah\x18\x03 \x01(\x05\x12\x13\n\x0bharga_akhir\x18\x04 \x01(\x02\x12\x19\n\x11tanggal_transaksi\x18\x05 \x01(\t\":\n\x11TransactionReport\x12%\n\ttransaksi\x18\x01 \x03(\x0b\x32\x12.kasir.Transaction2\x9e\x02\n\x07\x42\x61\x63kend\x12K\n\x12ProcessTransaction\x12\x19.kasir.TransactionRequest\x1a\x1a.kasir.TransactionResponse\x12\x35\n\nCheckStock\x12\x11.kasir.StockQuery\x1a\x14.kasir.StockResponse\x12\x44\n\x0bUpdateStock\x12\x19.kasir.StockUpdateRequest\x1a\x1a.kasir.StockUpdateResponse\x12I\n\x14GetTransactionReport\x12\x17.kasir.TransactionQuery\x1a\x18.kasir.TransactionReportb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kasir_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=22
  _globals['_TRANSACTIONREQUEST']._serialized_end=96
  _globals['_TRANSACTIONRESPONSE']._serialized_start=98
  _globals['_TRANSACTIONRESPONSE']._serialized_end=209
  _globals['_STOCKQUERY']._serialized_start=211
  _globals['_STOCKQUERY']._serialized_end=237
  _globals['_STOCKRESPONSE']._serialized_start=239
  _globals['_STOCKRESPONSE']._serialized_end=299
  _globals['_STOCKUPDATEREQUEST']._serialized_start=301
  _globals['_STOCKUPDATEREQUEST']._serialized_end=351
  _globals['_STOCKUPDATERESPONSE']._serialized_start=353
  _globals['_STOCKUPDATERESPONSE']._serialized_end=391
  _globals['_TRANSACTIONQUERY']._serialized_start=393
  _globals['_TRANSACTIONQUERY']._serialized_end=449
  _globals['_TRANSACTION']._serialized_start=451
  _globals['_TRANSACTION']._serialized_end=554
  _globals['_TRANSACTIONREPORT']._serialized_start=556
  _globals['_TRANSACTIONREPORT']._serialized_end=614
  _globals['_BACKEND']._serialized_start=617
  _globals['_BACKEND']._serialized_end=903
# @@protoc_insertion_point(module_scope)
